language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

addons:
  sonarcloud:
    organization: "kyaak-github"
    token:
      secure: "W3BNwC9uNk85qCO6MN74gYEpZ1J63iQ/1bDS7TE69QZzuvwzcyt4tRB5rH2YXXrDgxX+f+pNEKyordR3C92PKZDcUXTiLJH5eWWBJNKf37yv38dw7hrz48hoCzOXYkIuEO9nU9+SUmQUDTshy3h05cfJOKRQihvaRzucP7OJzb8vXX8UEY2V71Yf6xyxkAzvqogBxyr21yIh90WuSE7MCwFqu05bQIIXao7oILUAWRqh1zHZaIPEWSS8rdldbh9BXSWLHkCgYo6kajZHKo+fG5tol9MLkann5TiqVHoLkTjh76V6zDgWGa5EpMjnSxUKp8KkshVtF8u3QHKkFcFRV51s1t6XRYPKfDRtgOQ3+Yq2+F93L3MNtkgfmrgoKXsZ4Sdf9y2cwSGp+GH0YSjsaTcmC/K2irZuKEOtr44Ye3jfcDzMpZRiGgpvx2+cXXvGWvJoMaOWgyIjJbkjIBKAM4/Tq15uWnv7W5ajaQnxHH/gSaC3OwI3aebPjeJV5/RaBpOGK/MaYS8AohGY8HAlvM+UWRhcI2rZ9sMvMl/jQxjF3BiZwE2KpsNiyoQ8s/wDMJeC27uMFmljyiUXu77OWeWGRV3hWWeaWJLbRbWVJRzoIAsJ/PyZX0LudS5k5lJZePutHHxcf/rAHUyT/eMqbnFtIOOxyH0nR/esvPghz90="

script:
  - bundle exec rake spec
  - sonar-scanner

deploy:
  provider: rubygems
  api_key:
    secure: "Ce11z+EqDjKfZWe587qw024tfsjkyAhMVvLFGMHbtmXwXLGkJyWZl65t0jLdAyuD41kl7kzImz3ZckMpdFaAR/4m3Lh4iRkeXParv5mr/lE+veMFuAT3hI4pU+ha/Z0nqfPnBOpsqie884G3VD5U2FVtG6fSJ0Ht7wjmGJBy7V8ccmnpVvZnJu4mUVDAMszBRRRc3OoEik3xM+w6cAwh1rdwqKwiOGjrih84GIJd4YCzmZ9GK2hSzXaycVLO5M5155b81IiciTMlVBMHpHJtICQ6Qafm25pW5j0d1L1/YXK5OfA03vHOVCcw9u4kWjjJuMQKhSAdCFEBEMccDBjtwEPZwzpJtjNbQPs2oWuiHiWfSaumVQLHgjnaqjUjIjEQ/r1FOtziH65393AGVwleqjWXlG/0keSvXymP5yBMcwoj5gTpRN4Bsir14WE+QzVmX0wb2tXzqMFrCY8Z6MYJscoNLtbyFbqPvNuft4qjT75M9DUv3g2djbD/0CcjQT5QQgUR+o6Lt6jtMPM4Lyq76eWpn6wDCJmirf8eYg3ocVCc4rYLIUPMr+SgSk/PE2t3s4NCMWHVkTucfIqQ/70I+39dy4m+GkVJS8l8ZF2rHzA537isY7P7UX5J2D2mWYbY2IK8/iVQm4IX6cDxAZRdGlnUvbIC4iD6AMZVn/ve+bo="
  gem: danger-warnings
  on:
    branch: master
    rvm: 2.6
