language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6

addons:
  sonarcloud:
    organization: "kyaak-github"
    token:
      secure: "W3BNwC9uNk85qCO6MN74gYEpZ1J63iQ/1bDS7TE69QZzuvwzcyt4tRB5rH2YXXrDgxX+f+pNEKyordR3C92PKZDcUXTiLJH5eWWBJNKf37yv38dw7hrz48hoCzOXYkIuEO9nU9+SUmQUDTshy3h05cfJOKRQihvaRzucP7OJzb8vXX8UEY2V71Yf6xyxkAzvqogBxyr21yIh90WuSE7MCwFqu05bQIIXao7oILUAWRqh1zHZaIPEWSS8rdldbh9BXSWLHkCgYo6kajZHKo+fG5tol9MLkann5TiqVHoLkTjh76V6zDgWGa5EpMjnSxUKp8KkshVtF8u3QHKkFcFRV51s1t6XRYPKfDRtgOQ3+Yq2+F93L3MNtkgfmrgoKXsZ4Sdf9y2cwSGp+GH0YSjsaTcmC/K2irZuKEOtr44Ye3jfcDzMpZRiGgpvx2+cXXvGWvJoMaOWgyIjJbkjIBKAM4/Tq15uWnv7W5ajaQnxHH/gSaC3OwI3aebPjeJV5/RaBpOGK/MaYS8AohGY8HAlvM+UWRhcI2rZ9sMvMl/jQxjF3BiZwE2KpsNiyoQ8s/wDMJeC27uMFmljyiUXu77OWeWGRV3hWWeaWJLbRbWVJRzoIAsJ/PyZX0LudS5k5lJZePutHHxcf/rAHUyT/eMqbnFtIOOxyH0nR/esvPghz90="

env:
  global:
    - CC_TEST_REPORTER_ID=9226f0d36ca27b394a8c02615dcb54857e2ffbb5099288307016c5c78718dd98

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake spec
  - sonar-scanner

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

